remove duplicate mounting, check for mount before mounting

diff --git a/live-fat-stick b/live-fat-stick
--- a/live-fat-stick
+++ b/live-fat-stick
@@ -34,7 +34,7 @@ umount_everything () {
 	if [[ $distroname != isohybrid ]]; then
                 umount $isomount &>/dev/null             
                 umount $stickdevpart &>/dev/null
-		rm -rf $isomount &>/dev/null
+		rmdir $isomount &>/dev/null || echo "unable to remove $isomount, please remove manually"
                 umount $stickmount &>/dev/null
 		while $(mount | grep $stickmount &>/dev/null); do
 			umount $stickdevpart &>/dev/null
@@ -228,7 +228,6 @@ try_cp_with_progress () {
 	fi
 }
 copy_kernel_initrd () {
-	mount $stickdevpart $stickmount &>/dev/null
 	fuseiso $isopath $isomount &>/dev/null
 	echo "copying kernel and initrd from iso image to $stickdevpart"
 	if [[ $distroname == suse ]]; then
@@ -364,14 +363,25 @@ if [[ $distroname == isohybrid ]];then
 	try_cp_with_progress "$1" "$2"
 else
 	mkdir $isomount $stickmount &>/dev/null
+	if mount | grep $stickdevpart &>/dev/null; then
+		if ! umount $stickdevpart &>/dev/null; then
+			echo "$stickdevpart in use, please umount it before continuing"
+			exit 1
+		fi
+	fi
 	if ! mount $2 $stickmount &>/dev/null; then
 		echo "unable to mount the usb stick partition"
 		exit 1
 	fi
 	if [[ -e $stickmount/$isoname ]];then
 		isopath=$stickmount/$isoname
+		echo "using existing $isoname on the stick"
 	else
 		isopath=$iso_symlink
+		if [[ $distroname != fedora ]]; then
+			echo "copying $isoname to usb stick"
+			try_cp_with_progress "$1" "$stickmount/$isoname"
+		fi
 	fi
 	if [[ -f $stickmount/fatstick ]]; then
 		echo "the stick is already bootable stick"
@@ -387,14 +397,6 @@ else
 		add_menu_section
 	fi
 	touch $stickmount/fatstick
-	if [[ $distroname != fedora ]]; then
-		if [[ ! -f $stickmount/$isoname ]]; then
-			echo "copying $isoname to usb stick"
-			try_cp_with_progress "$1" "$stickmount/$isoname"
-		else
-			echo "using existing $isoname on the stick"
-		fi
-	fi
 	thisscript=$(readlink -f $0)
 	cp $thisscript $stickmount/ &>/dev/null || true
 fi
diff --git a/live-grub-stick b/live-grub-stick
--- a/live-grub-stick
+++ b/live-grub-stick
@@ -34,7 +34,7 @@ umount_everything () {
 	if [[ $distroname != isohybrid ]]; then
                 umount $isomount &>/dev/null             
                 umount $stickdevpart &>/dev/null
-		rm -rf $isomount &>/dev/null
+		rmdir $isomount &>/dev/null || echo "unable to remove $isomount, please remove manually"
                 umount $stickmount &>/dev/null
 		while $(mount | grep $stickmount &>/dev/null); do
 			umount $stickdevpart &>/dev/null
@@ -228,13 +228,12 @@ try_cp_with_progress () {
 	fi
 }
 cfg_setup() {
-	mount $stickdevpart $stickmount &>/dev/null
 	fuseiso $isopath $isomount &>/dev/null
 	if [[ -d $stickmount/boot ]];then
 		mkdir -p $stickmount/boot/
 	fi
 	if [[ $distroname == suse ]]; then
-		if [[ ! -f $stickmount/fatstick ]]; then
+		if [[ ! -f $stickmount/grubstick ]]; then
 			echo "copying grub2 files to $stickmount/boot/"
 			cp -r $isomount/boot/grub2 $stickmount/boot/
 		fi
@@ -367,16 +366,25 @@ if [[ $distroname == isohybrid ]];then
 	try_cp_with_progress "$1" "$2"
 else
 	mkdir $isomount $stickmount &>/dev/null
+	if mount | grep $stickdevpart &>/dev/null; then
+		if ! umount $stickdevpart &>/dev/null; then
+			echo "$stickdevpart in use, please umount it before continuing"
+			exit 1
+		fi
+	fi
 	if ! mount $2 $stickmount &>/dev/null; then
 		echo "unable to mount the usb stick partition"
 		exit 1
 	fi
 	if [[ -e $stickmount/$isoname ]];then
 		isopath=$stickmount/$isoname
+		echo "using existing $isoname on the stick"
 	else
 		isopath=$iso_symlink
+		echo "copying $isoname to usb stick"
+		try_cp_with_progress "$1" "$stickmount/$isoname"
 	fi
-	if [[ -f $stickmount/fatstick ]]; then
+	if [[ -f $stickmount/grubstick ]]; then
 		echo "the stick is already bootable stick"
 		if ! grep -q $isonameshort $grubcfgpath; then
 			echo "adding new image to boot menu"
@@ -389,13 +397,7 @@ else
 		create_grub_cfg
 		add_menu_section
 	fi
-	touch $stickmount/fatstick
-	if [[ ! -f $stickmount/$isoname ]]; then
-		echo "copying $isoname to usb stick"
-		try_cp_with_progress "$1" "$stickmount/$isoname"
-	else
-		echo "using existing $isoname on the stick"
-	fi
+	touch $stickmount/grubstick
 	thisscript=$(readlink -f $0)
 	cp $thisscript $stickmount/ &>/dev/null || true
 fi
