use fuseiso instead of mount, cleanups

diff --git a/live-fat-stick b/live-fat-stick
--- a/live-fat-stick
+++ b/live-fat-stick
@@ -23,7 +23,8 @@
 PATH=$PATH:/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin
 ionice -c3 -p$$
 umount_everything () {
-		sync
+	sync
+	if [[ $distroname != isohybrid ]]; then
                 umount $isomount &>/dev/null             
                 umount $stickdevpart &>/dev/null
 		rm -rf $isomount &>/dev/null
@@ -33,6 +34,7 @@ umount_everything () {
 			sleep 2
 		done
 		rmdir $stickmount &>/dev/null || echo "unable to remove $stickmount, please remove manually"
+	fi
 }
 clean_up () {
 	if [[ $1 == user_killed ]] ; then
@@ -136,6 +138,10 @@ if [[ ! -e /usr/bin/syslinux ]]; then
 	echo "syslinux not found, please install syslinux package"
 	exit 1
 fi
+if [[ ! -e /usr/bin/fuseiso ]]; then
+        echo "fuseiso not found, please install fuseiso package"
+        exit 1
+fi
 if [[ ! -e $1 ]]; then
 	echo "File $1 does not exist"
 	exit 1
@@ -163,6 +169,7 @@ stickpart=$(basename $2 | sed 's/[a-z]*//g')
 syslinuxpath=$stickmount/boot/syslinux
 stickdevpart=$2
 liveusbgui=/tmp/liveusbgui
+benice="nice ionice -c3"
 
 if [[ ! -h /dev/disk/by-uuid/$stickuuid ]]; then
         echo "wrong uuid detected, please file bug with output of: blkid $2"
@@ -183,21 +190,19 @@ are_you_sure ()  {
         done
 }
 try_cp_with_progress () {
-	if [ -x /usr/bin/dd_rescue ]; then
-		sync
-        	nice ionice -c3 dd_rescue -b 4M -y 4M "$1" "$2"
-		sync
-        	return
-	fi
-        if [[ $distroname == fedora ]]; then
-		nice ionice -c3 cp -r "$1/*" "$2"
+	sync
+        if [ -x /usr/bin/dd_rescue ]; then
+        	$benice dd_rescue -A -b 4M -y 4M "$1" "$2"
+	elif [ -x /usr/bin/ddrescue ]; then
+		$benice ddrescue --force --block-size=4M "$1" "$2"
 	else
-		nice ionice -c3 cp -r "$1" "$2"
+		echo "dd_rescue or ddrescue not found, please install one of them, using dd for now"
+		$benice dd if="$1" of="$2" bs=4M
 	fi
 }
 copy_kernel_initrd () {
 	mount $stickdevpart $stickmount &>/dev/null
-	mount -o loop $isopath $isomount &>/dev/null
+	fuseiso $isopath $isomount &>/dev/null
 	echo "copying kernel and initrd from iso image to $stickdevpart"
 	if [[ $distroname == suse ]]; then
 		rm $stickmount/syslinux.cfg &>/dev/null
@@ -227,11 +232,12 @@ copy_kernel_initrd () {
 		mkdir -p $syslinuxpath
 		mkdir -p $stickmount/$isonameshort
 		echo "copying the content of iso image, this may take a while"
-		try_cp_with_progress $isomount/ /$stickmount/$isonameshort/
+		$benice cp -r "$isomount/*" "/$stickmount/$isonameshort/"
 		mv $stickmount/$isonameshort/isolinux/initrd0.img $syslinuxpath/initrd-$isonameshort
 		mv $stickmount/$isonameshort/isolinux/vmlinuz0 $syslinuxpath/linux-$isonameshort
 		appendsection="append initrd=initrd-$isonameshort root=UUID=$stickuuid rootfstype=vfat rd.live.dir=/$isonameshort/LiveOS/ ro rd.live.image rd.luks=0 rd.md=0 rd.dm=0 quiet rhgb"
 	fi
+	umount $isomount &>/dev/null
 }
 syslinux_stuff () {
 	echo "installing syslinux on $stickdevpart"
@@ -324,7 +330,6 @@ if [[ ! -f $liveusbgui ]]; then
 	are_you_sure "continue ?" "y" "n"
 fi
 if [[ $distroname == isohybrid ]];then
-	echo "isohybrid image"
 	try_cp_with_progress $1 $2
 else
 	mkdir $isomount $stickmount &>/dev/null
@@ -336,10 +341,6 @@ else
 		isopath=$stickmount/$isoname
 	else
 		isopath=$1
-	fi
-	if ! mount -o loop $isopath $isomount &>/dev/null; then
-		echo "unable to mount the iso image"
-		exit 1
 	fi
 	if [[ -f $stickmount/fatstick ]]; then
 		echo "the stick is already bootable stick"
@@ -361,12 +362,13 @@ else
 	if [[ $distroname != fedora ]]; then
 		if [[ ! -f $stickmount/$isoname ]]; then
 			echo "copying $isoname to usb stick"
-			try_cp_with_progress $1 $stickmount/
+			try_cp_with_progress $1 $stickmount/$isoname
 		else
 			echo "using existing $isoname on the stick"
 		fi
 	fi
 	thisscript=$(readlink -f $0)
 	cp $thisscript $stickmount/ &>/dev/null || true
-	clean_up
 fi
+clean_up
+
