better handling of iso already on stick

diff --git a/live-fat-stick b/live-fat-stick
--- a/live-fat-stick
+++ b/live-fat-stick
@@ -19,15 +19,20 @@
 # Authors:      Jigish Gohil <cyberorg@opensuse.org>
 # This script creates bootable openSUSE live usb stick on fat partition
 #
+umount_everything () {
+		sync
+                umount $isomount &>/dev/null             
+                umount $stickmount && rm -rf $stickmount
+                umount $stickdevpart &>/dev/null
+}
 clean_up () {
-	sync
 	if [[ $1 == user_killed ]] ; then
 		echo "aborting and cleaning up"
-		umount $stickmount $isomount &>/dev/null && rm -rf $stickmount $isomount
+		umount_everything
 		exit
 	else
 		echo "cleaning up"
-		umount $stickmount $isomount &>/dev/null && rm -rf $stickmount $isomount
+		umount_everything
 		echo "Your bootable usb stick is now ready"
 		echo "have a lot of fun..."
 	fi
@@ -117,6 +122,7 @@ syslinux_stuff () {
 	echo "setting $stickdevice partition $stickpart active"
 	parted $stickdevice set $stickpart boot on &>/dev/null
 	mount $stickdevpart $stickmount &>/dev/null
+	mount $isopath $isomount &>/dev/null
 	echo "copying /boot from iso image to $stickdevpart"
 	cp -r $isomount/boot $stickmount/
 	rm $stickmount/syslinux.cfg &>/dev/null
@@ -169,12 +175,17 @@ echo "iso name: $isoname stick device: $stickdevice"
 echo "stick uuid: /dev/disk/by-uuid/$stickuuid stick partition: $stickpart"
 are_you_sure "continue ?" "y" "n"
 mkdir $isomount $stickmount &>/dev/null
-if ! mount $1 $isomount &>/dev/null; then
-	echo "unable to mount the iso image"
-	exit
-fi
 if ! mount $2 $stickmount &>/dev/null; then
-	echo "unable to mount the usb stick partition"
+        echo "unable to mount the usb stick partition"
+        exit
+fi
+if [[ -e $stickmount/$isoname ]];then
+	isopath=$stickmount/$isoname
+else
+	isopath=$1
+fi
+if ! mount $isopath $isomount &>/dev/null; then
+	echo "unable to mount the iso image"
 	exit
 fi
 if [[ -f $stickmount/fatstick ]]; then
@@ -188,6 +199,8 @@ if [[ -f $stickmount/fatstick ]]; then
 	fi
 else
 	umount $stickmount &>/dev/null || true
+	umount $stickdevpart &>/dev/null || true
+	umount $isopath &>/dev/null || true
 	syslinux_stuff
 	echo "creating menu entries"
 	cat <<EOF >$syslinuxpath/syslinux.cfg
@@ -203,10 +216,10 @@ EOF
 fi
 touch $stickmount/fatstick
 if [[ ! -f $stickmount/$isoname ]]; then
-	echo "copying $1 to usb stick"
+	echo "copying $isoname to usb stick"
 	cp $1 $stickmount/
 else
-	echo "$isoname already exists on the stick, doing nothing"
+	echo "using existing $isoname on the stick"
 fi
 clean_up
 
